### ISSUE TITLE
What needs to be done

### ISSUE THREAD

**Issue by firasalkafri** [edx/edx-enterprise#10]
Any clear plan on what needs to be done? How can I contribute?

**Comment by mattdrayer** [comment]
Hey there, @firasalkafri!  Thanks so much for contacting us.  The edX Solutions team is currently working on the MVP for this component.  We are hoping to deliver the initial set of functionality by the end of the year.  We'll be available to support the Open edX community with new enhancements after the MVP has shipped.

If you can take a minute to let us know how you would like to contribute to this project, if you would be working solo or with a team, and a general idea of your availability, that would be helpful, thanks!

**Comment by e-kolpakov** [comment]
@firasalkafri Are you still interested in this issue? Totally OK if you're not, but I'd like to close this issue otherwise.

**Comment by haikuginger** [comment]
I'm closing this, as we don't appear to have had any further response.

**Comment by firasalkafri** [comment]
Apologies guys been pretty busy.

@mattdrayer Definitely.

**Comment by mattdrayer** [comment]
@douglashall
