### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by coldice** [edx/edx-enterprise#38]
The documentation (https://edx-enterprise.readthedocs.org) seems not to be existent anymore? Or is it not existing yet?

**Comment by bradenmacdonald** [comment]
We're working on it :) 

https://github.com/edx/edx-enterprise/pull/35

**Comment by coldice** [comment]
Sorry for commenting on this closed issue, but thank you very much for pointing me there. I just found this project in the edx group and was curious about what it is, reading the first section of the development section doc in the PR really helped me 👍

**Comment by bradenmacdonald** [comment]
Glad to hear that!
