### ISSUE TITLE
Configure Cornerstone integrated channel?

### ISSUE THREAD

**Issue by peeushb** [edx/edx-enterprise#633]
* Ironwood release, master branch:

### Description

I can see there are a couple of Enterprise Customer configuration options available in the django admin application (<your install URL>/admin):

ENTERPRISE DEGREED INTEGRATION -> Degreed enterprise customer configurations and ENTERPRISE SAP SUCCESSFACTORS INTEGRATION -> Sap success factors enterprise customer configurations

There are no configuration options available for Cornerstone, even though Cornerstone is already available as an integrated channel on the edx-enterprise github project

Has anyone configured Cornerstone integration with Open Edx and can provide pointers on how to go about implementing and configuring Cornerstone integrated channel?

### What I Did
I have been playing with various options available under THIRD-PARTY AUTHENTICATION options (oAuth, SAML etc.) but not sure how to make it work if that's the way to go.

**Comment by nedbat** [comment]
We can't provide support in GitHub issues.  The discussion forum is a better place: https://openedx.org/getting-help.

**Comment by peeushb** [comment]
Thanks Ned! I have logged this on Open Edx Community forum as well: https://discuss.openedx.org/t/configure-cornerstone-integrated-channel/914
